// Chunky 1-bit silhouette of the Marimar Inn tulip mark, for cheap 58mm ESC/POS. Solid black, 48x40.
export const RECEIPT_ICON_WIDTH = 48;
export const RECEIPT_ICON_HEIGHT = 40;
export const RECEIPT_ICON_BASE64 =
  "AAAAAAAAAAAAAAAAAAwAADAAAAwAADAAAA8AAPAAAAeAAfAAAAfAA/AAAAfgB/AADAfwD/AwD4/4H/HwB//4H//gB/8cOP/gB/8M"
  "MP/gB/8H4P/gB4+H4fHgB4/H4/HgB4////HgB4////HgB44//HHgB44cOHHgB44MMHHgB44EIHHgB44DwHHgB44DwHHgB44AAHHg"
  "B44AAHHgA44AAHHAA48AAPHAA/8AAP+AAf8AAf+AAP+AAf8AAP/AA/4AAD/gB/wAABwwDDgAAAQAACAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAA";
export const RECEIPT_ICON_PNG_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAoAQAAAACQ/ETcAAAAn0lEQVR4nG2PQQqCUBCGvzcKulJvYN"
  "DFOoI30KO5CGqXBwgSWrQVciEk/vFeWBHNYn6+mfmZGSd8WMgYI3QroUHKZaSNwki7BOlnsJFhomOokj7LmUh6SoPzLYwUKTAxlb"
  "5YNcpWewxHAr32uTZqPG33b59BWgRxu6/LiNoPxT5vDEEDMxK1GZ4R9YLCPofR9rNvXE/3g9BDusj9PP1HnhnNO3uqehH1AAAAAE"
  "lFTkSuQmCC";
